# Generated by Django 6.0.3 on 2026-05-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medico', models.CharField(max_length=100)),
                ('horario_disponible', models.TimeField()),
                ('fecha_disponible', models.DateField()),
                ('sede_disponible', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('estado', models.CharField(default='Disponible', max_length=50)),
            ],
        ),
    ]
