# Generated by Django 6.0.3 on 2026-05-19 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cita', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='paciente',
        ),
        migrations.AddField(
            model_name='cita',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HorarioDoctor',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
