# Generated by Django 6.0.3 on 2026-05-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cita', '0002_remove_paciente_usuario_remove_cita_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
