# Generated by Django 6.0.4 on 2026-05-19 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cita', '0003_doctor_nombre'),
        ('historia_clinica', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='paciente',
        ),
        migrations.RenameField(
            model_name='historiaclinica',
            old_name='actualizacion',
            new_name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='motivo_consulta',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='tratamiento',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='alergias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='antecedentes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='enfermedades_cronicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='observaciones_generales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintomas', models.TextField()),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('receta', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_cita.cita')),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historia_clinica.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_examen', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('resultado', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='resultados_examenes/')),
                ('fecha_examen', models.DateField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historia_clinica.consultamedica')),
            ],
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
