# Generated by Django 6.0.3 on 2026-03-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispensacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=30)),
                ('paciente', models.CharField(max_length=90)),
                ('cantidad', models.IntegerField()),
                ('fecha_entrega', models.DateField(auto_now_add=True)),
                ('indicaciones_medicas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('laboratorio', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('requiere_formula', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
