# Generated by Django 6.0.3 on 2026-05-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispensacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=30)),
                ('paciente', models.CharField(max_length=90)),
                ('cantidad', models.IntegerField()),
                ('fecha_entrega', models.DateField(auto_now_add=True)),
                ('indicaciones_medicas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('laboratorio', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('requiere_formula', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('horario', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=90)),
                ('medicamento', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('fecha_agendada', models.DateField()),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
    ]
